[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"
