[server]
headless = true
port = $PORT  # Let Render assign the port dynamically
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#4DC4D2"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
favicon = "favicon.png"
